name: Deploy EKS Cluster

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2   

      - name: Initialize Terraform
        run: terraform init   

      - name: Terraform Plan
        run: terraform plan 

      - name: Apply Terraform
        run: terraform apply -auto-approve
